apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../client
patches:
  - target:
      kind: Deployment
      name: hello-client
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      # Set restricted PodSecurity context
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      - op: replace
        path: /spec/template/spec/containers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext
        value:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
      # Replace hostPath volume with SPIFFE CSI driver ephemeral volume
      - op: replace
        path: /spec/template/spec/volumes/0
        value:
          name: spire-agent-socket
          csi:
            driver: "csi.spiffe.io"
            readOnly: true
