apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: hello-client
spec:
  className: zero-trust-workload-identity-manager-spire
  spiffeIDTemplate: "spiffe://public.demo.example.com/hello-client"
  podSelector:
    matchLabels:
      app: hello-client
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: client
  federatesWith:
    - "private.demo.example.com"
