apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - zero-trust-workload-identity-manager.yml
  - spire-server.yml
  - spire-agent.yml
  - spiffe-csi-driver.yml
  - cluster-spiffe-id.yml
