apiVersion: operator.openshift.io/v1alpha1
kind: ZeroTrustWorkloadIdentityManager
metadata:
  name: cluster
spec:
  trustDomain: public.demo.example.com
  clusterName: public
  bundleConfigMap: spire-bundle
