agent_address = "/run/spire/sockets/agent.sock"
cert_dir = "/opt/spiffe-certs"
daemon_mode = true

svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
