apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - server-rbac.yml
  - server-statefulset.yml
  - agent-rbac.yml
  - agent-daemonset.yml
images:
  - name: ghcr.io/spiffe/spire-server
    newTag: "1.9.4"
  - name: ghcr.io/spiffe/spire-agent
    newTag: "1.9.4"
