apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../server
  - scc.yml
patches:
  - target:
      kind: Deployment
      name: hello-server
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/initContainers/0/securityContext
        value:
          runAsUser: 185
          seLinuxOptions:
            type: spc_t
          capabilities:
            add: ["DAC_OVERRIDE"]
