# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8080/realms/demo
quarkus.oidc.client-id=authorization-demo
quarkus.oidc.credentials.secret=authorization-demo-secret
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/
quarkus.oidc.roles.source=accesstoken
quarkus.oidc.token.principal-claim=preferred_username

# Keycloak Policy Enforcer
quarkus.keycloak.policy-enforcer.enabled=true
quarkus.keycloak.policy-enforcer.lazy-load-paths=false

# HTTP
quarkus.http.port=8081
