apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-spiffe-csi-driver
  namespace: spire
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.spiffe.io
  labels:
    security.openshift.io/csi-ephemeral-volume-profile: restricted
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Ephemeral
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: spire-spiffe-csi-driver
  namespace: spire
spec:
  selector:
    matchLabels:
      app: spiffe-csi-driver
  template:
    metadata:
      labels:
        app: spiffe-csi-driver
    spec:
      serviceAccountName: spire-spiffe-csi-driver
      initContainers:
        - name: set-context
          image: registry.access.redhat.com/ubi9
          command: ["chcon", "-Rvt", "container_file_t", "spire-agent-socket/"]
          securityContext:
            privileged: true
            capabilities:
              drop: ["all"]
          volumeMounts:
            - name: spire-agent-socket-dir
              mountPath: /spire-agent-socket
      containers:
        - name: spiffe-csi-driver
          image: ghcr.io/spiffe/spiffe-csi-driver:0.2.6
          args:
            - -workload-api-socket-dir
            - /spire-agent-socket
            - -plugin-name
            - csi.spiffe.io
            - -csi-socket-path
            - /spiffe-csi/csi.sock
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["all"]
          volumeMounts:
            - name: spire-agent-socket-dir
              mountPath: /spire-agent-socket
              readOnly: true
            - name: spiffe-csi-socket-dir
              mountPath: /spiffe-csi
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
        - name: node-driver-registrar
          image: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel9
          args:
            - -csi-address
            - /spiffe-csi/csi.sock
            - -kubelet-registration-path
            - /var/lib/kubelet/plugins/csi.spiffe.io/csi.sock
            - -health-port
            - "9809"
          ports:
            - name: healthz
              containerPort: 9809
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 5
            periodSeconds: 10
          securityContext:
            privileged: true
            capabilities:
              drop: ["all"]
          volumeMounts:
            - name: spiffe-csi-socket-dir
              mountPath: /spiffe-csi
            - name: kubelet-plugin-registration-dir
              mountPath: /registration
      volumes:
        - name: spire-agent-socket-dir
          hostPath:
            path: /run/spire/agent-sockets
            type: DirectoryOrCreate
        - name: spiffe-csi-socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.spiffe.io
            type: DirectoryOrCreate
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: Directory
        - name: kubelet-plugin-registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
