apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../spire/base
  - scc.yml
  - csi-driver.yml
patches:
  # Add spire-spiffe-csi-driver ServiceAccount (OpenShift-only)
  - target:
      kind: DaemonSet
      name: spire-agent
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/securityContext
        value:
          privileged: true
