apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yml
  - rbac.yml
  - scc.yml
  - services.yml
  - server-statefulset.yml
  - agent-daemonset.yml
  - csi-driver.yml
  - spire-bundle-configmap.yml
