apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: spire-agent
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: []
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
users:
  - system:serviceaccount:spire:spire-agent
volumes:
  - configMap
  - emptyDir
  - hostPath
  - projected
  - secret
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: spire-spiffe-csi-driver
allowHostDirVolumePlugin: true
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities: null
defaultAddCapabilities: []
fsGroup:
  type: MustRunAs
groups: []
readOnlyRootFilesystem: true
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsRange
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: MustRunAs
users:
  - system:serviceaccount:spire:spire-spiffe-csi-driver
volumes:
  - configMap
  - hostPath
  - secret
