apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-config
  namespace: spire
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "public.demo.example.com"
      data_dir = "/run/spire/data"
      log_level = "INFO"
      ca_ttl = "12h"
      default_x509_svid_ttl = "1h"
      jwt_issuer = "spire-public.spire.svc.cluster.local"
      ca_key_type = "rsa-2048"
      ca_subject = {
        country = ["US"],
        organization = ["SPIFFE"],
        common_name = "",
      }
      federation {
        bundle_endpoint {
          address = "0.0.0.0"
          port = 8443
          profile "https_web" {
            serving_cert_file {
              cert_file_path = "/run/spire/server-tls/tls.crt"
              key_file_path = "/run/spire/server-tls/tls.key"
              file_sync_interval = "1h"
            }
          }
        }
      }
    }
    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "sqlite3"
          connection_string = "/run/spire/data/datastore.sqlite3"
        }
      }
      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "minikube" = {
              service_account_allow_list = ["spire:spire-agent"]
              audience = ["spire-server"]
            }
          }
        }
      }
      KeyManager "disk" {
        plugin_data {
          keys_path = "/run/spire/data/keys.json"
        }
      }
      Notifier "k8sbundle" {
        plugin_data {
          config_map = "spire-bundle"
          namespace = "spire"
        }
      }
    }
    health_checks {
      bind_address = "0.0.0.0"
      bind_port = "8080"
      listener_enabled = true
      live_path = "/live"
      ready_path = "/ready"
    }
