quarkus.application.name=microservice2
quarkus.http.port=8083

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/demo
quarkus.oidc.client-id=microservice2
quarkus.oidc.credentials.secret=microservice2-secret
quarkus.oidc.application-type=service
