agent_address = "/run/spire/sockets/agent.sock"
cert_dir = "/opt/spiffe-certs"
daemon_mode = true

svid_file_name = "client.crt"
svid_key_file_name = "client.key"
svid_bundle_file_name = "bundle.pem"
