# HTTP Port
quarkus.http.port=8081
quarkus.log.category."io.quarkus.oidc".level=DEBUG

# OIDC Authentication Configuration

quarkus.oidc.auth-server-url=http://localhost:8080/realms/realm1
#quarkus.oidc.token.claims.role.claim=realm_access.roles
quarkus.oidc.application-type=service

# Per tenant configuration
## Backend
#quarkus.oidc.tenant-enabled=true
#quarkus.oidc.default-tenant.enabled=false
#quarkus.oidc.backend.auth-server-url=http://localhost:8080/realms/realm1
#quarkus.oidc.backend.token.claims.role.claim=realm_access.roles
#quarkus.oidc.backend.client-id=backend
#quarkus.oidc.backend.credentials.secret=test
#quarkus.oidc.backend.application-type=service



## Frontend
#quarkus.oidc.tenant.frontend.client-id=myclient
#quarkus.oidc.tenant.frontend.credentials.secret=test
#quarkus.oidc.tenant.frontend.application-type=web-app
#quarkus.oidc.tenant.frontend.authentication.redirect-path=/
