FROM quay.io/remerson/keycloak:0.0.1-97fef0 AS builder
ADD --chmod=644 https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc11/23.7.0.25.01/ojdbc11-23.7.0.25.01.jar /opt/keycloak/providers/ojdbc11.jar

FROM quay.io/remerson/keycloak:0.0.1-97fef0
COPY --from=builder /opt/keycloak/providers/ojdbc11.jar /opt/keycloak/providers/ojdbc11.jar
