apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: hello-client
spec:
  className: zero-trust-workload-identity-manager-spire
  spiffeIDTemplate: "spiffe://public.demo.example.com/hello-client"
  podSelector:
    matchLabels:
      app: hello-client
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: client
  federatesWith:
    - "private.demo.example.com"
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: keycloak
spec:
  className: zero-trust-workload-identity-manager-spire
  spiffeIDTemplate: "spiffe://public.demo.example.com/keycloak"
  podSelector:
    matchLabels:
      app: keycloak
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: keycloak
  dnsNameTemplates:
    - "keycloak.keycloak.svc.cluster.local" # Allows kcadm.sh hostname verification to work as expected \
  federatesWith:
    - "private.demo.example.com"
