keyStorePath = /opt/spiffe-certs/keystore.p12
keyStorePass = changeit
keyPass = changeit
trustStorePath = /opt/spiffe-certs/truststore.p12
trustStorePass = changeit
keyStoreType = pkcs12
keyAlias = spiffe
spiffeSocketPath = unix:/run/spire/sockets/agent.sock
