quarkus.application.name=frontend
quarkus.http.port=8081

quarkus.oidc.auth-server-url=http://keycloak:8080/realms/demo
quarkus.oidc.client-id=frontend
quarkus.oidc.credentials.jwt.audience=https://microservice1:8082
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/

quarkus.rest-client.microservice1.url=http://microservice1:8082
