log_level = "DEBUG"
domains = ["spire-oidc"]

serving_cert_file {
    addr = ":443"
    cert_file_path = "/opt/spiffe-certs/svid.pem"
    key_file_path = "/opt/spiffe-certs/svid_key.pem"
}

server_api {
    address = "unix:///tmp/spire-server/private/api.sock"
}

health_checks {}
