quarkus.oidc.auth-server-url=http://localhost:8081/realms/demo
quarkus.oidc.client-id=bret-fisher-service
quarkus.oidc.credentials.secret=EhkEtg0YXPlAmrOOKKJKzcVYrk4MZ2nV
quarkus.oidc.application-type=web-app
quarkus.oidc.authentication.redirect-path=/users/me
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/