apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  selector:
    app: spire-server
  ports:
  - name: grpc
    port: 8081
    targetPort: 8081
  - name: https
    port: 443
    targetPort: 8443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spire-server
  namespace: spire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-server
  serviceName: spire-server
  template:
    metadata:
      labels:
        app: spire-server
    spec:
      serviceAccountName: spire-server
      containers:
      - name: spire-server
        image: ghcr.io/spiffe/spire-server
        args: ["-config", "/run/spire/config/server.conf"]
        ports:
        - containerPort: 8081
        - containerPort: 8443
        volumeMounts:
        - name: spire-server-config
          mountPath: /run/spire/config
          readOnly: true
        - name: spire-data
          mountPath: /run/spire/data
        - name: spire-server-socket
          mountPath: /tmp/spire-server/private
          readOnly: false
        - name: spire-federation-cert
          mountPath: /run/spire/federation-cert
          readOnly: true
        readinessProbe:
          exec:
            command:
            - /opt/spire/bin/spire-server
            - healthcheck
            - -socketPath
            - /tmp/spire-server/private/api.sock
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: spire-server-config
        configMap:
          name: spire-server-config
      - name: spire-agent-socket
        hostPath:
          path: /run/spire/socket
          type: DirectoryOrCreate
      - name: spire-data
        emptyDir: {}
      - name: spire-server-socket
        emptyDir: {}
      - name: spire-federation-cert
        secret:
          secretName: spire-federation-cert
