# A list of SPIFFE IDs separated by '|' to trust or '*' to trust all
spiffe.ids=*
spiffe.tls=mtls
server.url=https://hello-server.server.svc.cluster.local:8443

# --- Logging ---
quarkus.log.level=INFO
quarkus.log.category."com.example.spiffe".level=DEBUG

# java-spiffe bundle fetching and SVID updates
quarkus.log.category."io.spiffe".level=DEBUG
