apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../spire/private
  - scc.yml
patches:
  - target:
      kind: StatefulSet
      name: spire-server
    patch: |
      - op: remove
        path: /spec/template/spec/volumes/1
